### PR TITLE
Infra 15754 - fix year end processing

### PR DESCRIPTION
**Pull request by sebbASF**
Also fixes misplaced exit statement

### CODE REVIEW

**Comment by sebbASF** [comment]
Note: the file now agrees with

https://svn.apache.org/repos/asf/httpd/mod_mbox/trunk/scripts/update-index-monthly

However gzcat has been changed to zcat.

**Comment by gmcdonald** [comment]
That's fine I guess. I've had other scripts determine which to use depending on OS, but not really required here.

**Comment by gmcdonald** [comment]
Are you happy for this to be merged now?

**Comment by sebbASF** [comment]
Yes, fine to be merged.
My comment was just intended to note that the local copy now agrees with the original apart from the necessary zcat change. (I've raised a bug for the hard-coded name).

**Pull request merged**
