### PR TITLE
[INFRA-19541] proxying ssl to plugins.netbeans.org

### PR DESCRIPTION
**Pull request by vieiro**
Proposed change to the netbeans-vm.apache.org.yaml configuration to proxy requests 
https://netbeans-vm.apache.org/pluginportal2/updates/11.0/catalog.xml.gz
to
http://plugins.netbeans.org/updates/11.0/catalog.xml.gz

### CODE REVIEW

**Comment by Humbedooh** [comment]
Ditch the rewriteengine and rewriterule and just have:
ProxyPass /updates/11.0/ http://plugins.netbeans.org/nbpluginportal/updates/11.0/

**Comment by vieiro** [comment]
Thanks, @Humbedooh! On the works!

**Comment by vieiro** [comment]
@Humbedooh done!

**Comment by Humbedooh** [comment]
Please don't proxypass from within a <Directory> stanza, that is asking for arbitrary things to happen. Do it in the vhost root or in a <Location> stanza.

**Pull request merged**
