### PR TITLE
Fix alignment in generated file

### PR DESCRIPTION
**Pull request by sebbASF**

### CODE REVIEW

**Comment by gstein** [comment]
I don't know Ruby well enough, but it looks like the commit message may be incorrect: how does this fix alignment? It looks more like it just removes a named match from the regex. ?

**Comment by sebbASF** [comment]
It fixes the alignment by ensuring that all lines start with the same indent.
The existing code only replaces whatever happens to match the first leading spaces.
rubys can confirm if necessary

**Comment by gstein** [comment]
Thx. yeah... I'm gonna defer to another with Ruby skillz...

**Comment by rubys** [comment]
Logic before: find the first line with indentation, and then replace that amount of indentation in all lines with two spaces.

Logic after: replace all indentation with two spaces.

The code before understood that some of the data had nested indents.  (Things like &lt;LocationMatch> and the like).

**Comment by gstein** [comment]
okay... so, variant indents are not preserved: every indent gets switched to two spaces. ... Losing the variance doesn't sound helpful.

**Comment by sebbASF** [comment]
At the moment the generated output looks like this:

```
<Directory /x1/srv/whimsy/www/test/roster>
AuthType Basic
  AuthName "ASF Committers"
  AuthBasicProvider ldap
  AuthLDAPUrl "ldaps://ldap2-us-west.apache.org:636 ldap1-us-west.apache.org:636/ou=people,dc=apache,dc=org?uid"
  AuthLDAPGroupAttribute memberUid
  AuthLDAPGroupAttributeIsDN off
  Require ldap-group cn=committers,ou=groups,dc=apache,dc=org
</Directory>

<LocationMatch ^/incubator/moderators>
AuthType Basic
  AuthName "ASF Members and Incubator PMC"
  AuthBasicProvider ldap
  AuthLDAPUrl "ldaps://ldap2-us-west.apache.org:636 ldap1-us-west.apache.org:636/ou=people,dc=apache,dc=org?uid"
  AuthLDAPGroupAttribute memberUid
  AuthLDAPGroupAttributeIsDN off
  Require ldap-group cn=committers,ou=groups,dc=apache,dc=org
</LocationMatch>
```

Which is harder to read.

**Comment by rubys** [comment]
I agree that this could be improved.  I suggest that the problem is in the call to strip which removes the whitespace from the first line.  A better replacement:

```
content = content[1..-2].gsub /^#{content[/^\s+/]}/, '  '
```

**Comment by rubys** [comment]
:+1:

**Comment by sebbASF** [comment]
Unfortunately it hasn't worked properly.
Although the individual elements now have the same alignment, it is too deep.
And there are spurious trailing blank lines.

For example, the sample above has become:

```
<Directory /x1/srv/whimsy/www/test/roster>
            AuthType Basic
            AuthName "ASF Committers"
            AuthBasicProvider ldap
            AuthLDAPUrl "ldaps://ldap2-us-west.apache.org:636 ldap1-us-west.apache.org:636/ou=people,dc=apache,dc=org?uid"
            AuthLDAPGroupAttribute memberUid
            AuthLDAPGroupAttributeIsDN off
            Require ldap-group cn=committers,ou=groups,dc=apache,dc=org
         
</Directory>

<LocationMatch ^/incubator/moderators>
            AuthType Basic
            AuthName "ASF Members and Incubator PMC"
            AuthBasicProvider ldap
            AuthLDAPUrl "ldaps://ldap2-us-west.apache.org:636 ldap1-us-west.apache.org:636/ou=people,dc=apache,dc=org?uid"
            AuthLDAPGroupAttribute memberUid
            AuthLDAPGroupAttributeIsDN off
            Require ldap-group cn=committers,ou=groups,dc=apache,dc=org
         
</LocationMatch>
```

As a result of the increased indentation, nested alignment is broken:

```
<LocationMatch ^/board/publish_minutes>
            AuthType Basic
            AuthName "ASF Secretarial Team"
            AuthBasicProvider ldap
            AuthLDAPUrl "ldaps://ldap2-us-west.apache.org:636 ldap1-us-west.apache.org:636/ou=people,dc=apache,dc=org?uid"
            AuthLDAPGroupAttribute member
            AuthLDAPGroupAttributeIsDN on
            <RequireAny>
    Require ldap-group cn=asf-secretary,ou=groups,ou=services,dc=apache,dc=org
    Require ldap-group cn=apldap,ou=groups,ou=services,dc=apache,dc=org
  </RequireAny>
         
</LocationMatch>
```

**Comment by rubys** [comment]
I've made a pull request with a fix: https://github.com/apache/infrastructure-puppet/pull/270/commits/f0f1524e22d44c6d03edda1550309be7b1be54e8

I've also added test scaffolding which will be useful in the future: https://github.com/apache/whimsy/blob/master/tools/vhosttest.rb

**Pull request merged**
