### PR TITLE
INFRA-12291 first attempt at configuring gump's httpd

### PR DESCRIPTION
**Pull request by bodewig**

### CODE REVIEW

**Comment by gmcdonald** [comment]
I see you removed ant and tomcat also by overriding in the yaml the base packages. That is fine, but that should have been a different commit (same push is fine) with a commit message that explains this change. iow, it has nothing to do with the setting up of httpd.

**Comment by bodewig** [comment]
I've split it (and rebased the branch again), thought you'd prefer a squashed commit, sorry. :-)

**Comment by gmcdonald** [comment]
merged, looks to be working well

**Comment by bodewig** [comment]
Yes, looks good, I may need to take core of https in a way (HTTPS everywhere sends me there and it looks broken). I'll need a few more steps but hope to finish the migration within the next week or so.

Thanks.

**Pull request merged**
