### PR TITLE
Update Camel staging site source

### PR DESCRIPTION
**Pull request by zregvart**
I think this is the right configuration. From GitBox repository `camel-website`'s `asf-site` branch to camel.apache.org/staging.

@clambertus can you take a look?

### CODE REVIEW

**Comment by zregvart** [comment]
This relates to https://issues.apache.org/jira/browse/INFRA-15969

**Comment by Humbedooh** [comment]
if you're using asf-site, the ":asf-site" becomes unnecessary, as that is the default.

**Comment by zregvart** [comment]
Thanks @Humbedooh let me fix that.

**Comment by zregvart** [comment]
Thank you :100:

**Pull request merged**
