### PR TITLE
Fetch projects.json

### PR DESCRIPTION
**Pull request by sebbASF**
home.a.o needs to use ldap_projects.json

### CODE REVIEW

**Comment by pono** [comment]
I'm happy to merge this, but curious why it needs this file.

**Comment by sebbASF** [comment]
home.a.o provides info on committees and podlings.

These are now in projects.json which will eventually take over from groups, committees and nonldap_groups.

**Comment by clambertus** [comment]
Are you referring to home.a.o/phonebook? isn't this almost entirely superseded by whimsy's roster tool at this point?

**Comment by sebbASF** [comment]
Whilst Whimsy provides much the same functionality as phonebook, it requires a committer login.
Phonebook is much faster, though it is not as up to date.

Also home.a.o creates the keys files which Whimsy does not.
That is what needs the extra file copy.

However if someone wants to take the decision to retire the home.a.o functions, I can look into providing redirects to the relevant Whimsy URLs.

**Pull request merged**
