### PR TITLE
Re: https://issues.apache.org/jira/browse/INFRA-11960

### PR DESCRIPTION
**Pull request by PierreSmits**
- adding proxy_ajp configuration
- adding letsencrypt configuration
- adding vhost for ofbiz-demo-trunk (both re port 80 and port 443) against OFBiz via 8009
- adding vhost for ofbiz-demo-stable (both re port 80 and port 443) against OFBiz via 18009
- adding vhost for ofbiz-demo-old (both re port 80 and port 443) against OFBiz via 28009
- adding vhost regarding bigfiles via port 8443

### CODE REVIEW

**Comment by clambertus** [comment]
The letsencrypt path will need to be updated to /etc/letsencrypt/live/ofbiz-vm2.apache.org/*.pem for all the vhosts. It uses the first name in the domain list to generate the certificate filename, and all of the domains are included in the same cert as alternate names.

**Comment by PierreSmits** [comment]
Thanks for the review, Chris.

I will take of the required changes.

Can you take care of the adjustment in the dns, by adding:
* ofbiz-demo-trunk.apache.org
* ofbiz-demo-stable.apache.org
* ofbiz-demo-old.apache.org
?

**Comment by PierreSmits** [comment]
Chris,
Are the settings regarding vhost_name and servername for each of the vhosts correct?

**Comment by clambertus** [comment]
They should probably all be vhost_name: '*' -- as for the DNS, please file an infra jira to get the DNS names added.

**Comment by PierreSmits** [comment]
I will leave vhost_name refs as they are at the moment. See how that works out.

**Comment by gmcdonald** [comment]
Im going to reject this sorry based on what I said also in INFRA-13173 - that is you need to be using entries as sub-domains of ofbiz.apache.org not of apache.org.

So please rewrite as:-

demo-trunk.ofbiz.apache.org
demo-stable.ofbiz.apache.org
demo-old.ofbiz.apache.org 

thanks.

**Comment by JacquesLeRoux** [comment]
Thanks for adding Java 8, Pierre

I put some other comments at https://issues.apache.org/jira/browse/INFRA-13173 and voted to push this change

**Pull request merged**
