### PR TITLE
We don't need SSL and certificate for videos!

### PR DESCRIPTION
**Pull request by JacquesLeRoux**
Trying to fix the certificate issue we have with OFBiz demos

### CODE REVIEW

**Comment by PierreSmits** [comment]
This is not going to fly when you leave 'RedirectMatch permanent ^/(.*)$ https://ofbiz-vm2.apache.org/$1' in place.

**Comment by JacquesLeRoux** [comment]
Right Pierre, it's indeed useless now. I'll fix that!

**Comment by PierreSmits** [comment]
It was working, right?

So now we don't have a secure path to ofbiz-vm2.apache.org, a letsencrypt config that is not going to be used...

**Comment by JacquesLeRoux** [comment]
The whole was not working as reported at OFBIZ-9206 and INFRA-11960. So I try to make the setup as simple as possible. For instance we don't need a certificate to shows static files (videos and such). If you have better ideas please share...

**Comment by PierreSmits** [comment]
It is working. See https://ofbiz-vm2.apache.org/FrameworkIntro/

I wonder why we would go through all this trouble to correct a working setup. I recommend to leave it as is.

**Comment by PierreSmits** [comment]
The only part that is not working is the backend OFBiz demos (see earlier mentioned JIRA issues), which is due to OFBiz demo specific setups. The letsencrypt and httpd configs work as intended,  see:
https://demo-old.ofbiz.apache.org/catalog/control/main
https://demo-stable.ofbiz.apache.org/catalog/control/main
https://demo-trunk.ofbiz.apache.org/catalog/control/main

**Comment by JacquesLeRoux** [comment]
Right, I also tried from there https://cwiki.apache.org/confluence/display/OFBIZ/Framework+Introduction+Videos+and+Diagrams. I'll remove my change it's useless.

The pb is indeed that OFBiz is adding the port 8443. I'll check why the demos are doing that.

**Pull request closed without merging**
