### PR TITLE
Update drat-vm.apache.org.yaml

### PR DESCRIPTION
**Pull request by chrismattmann**
Please point this path to our new DRAT proteus app - we are gearing up to release a 1.0-RC1 candidate and this will be the updated path.

### CODE REVIEW

**Comment by clambertus** [comment]
looks good to me

**Comment by chrismattmann** [comment]
thanks @clambertus how do I get this to redeploy? I go to http://drat.apache.org/demo/ and it points to the old app, and I go to http://drat-vm.apache.org/demo/ and it points to the old app?

**Comment by clambertus** [comment]
I missed that you opened this PR against your own branch rather than the deployment branch. I've fixed it in #1130. It should go live in 20 minutes or so.

**Comment by chrismattmann** [comment]
thanks @clambertus it doesn't seem to be working. 
Also can you point me at the repo for drat.apache.org puppet? - we have a few redirects there I need to update too. Thanks!

**Comment by clambertus** [comment]
open a ticket please

**Comment by chrismattmann** [comment]
sure you got it, I will open a new ticket, for sure. @clambertus can you please point me though at the puppet file for drat.apache.org so I can submit a PR there? Thanks.

**Pull request merged**
