### PR TITLE
turn gunicorn viewvc into a service

### PR DESCRIPTION
**Pull request by pono**
ignore the puppetfile nonsense

### CODE REVIEW

**Comment by Humbedooh** [comment]
🍔🍔🍔 (testing unicode)

**Comment by Humbedooh** [comment]
🍔🍔🍔🍔 bit more testing

**Comment by Humbedooh** [comment]
should be text/plain, silly
🍔🍔🍔🍔

**Comment by tonymontana100** [comment]
Root

**Pull request closed without merging**
