### PR TITLE
Gen httpdconfig rework

### PR DESCRIPTION
**Pull request by sebbASF**
General tidyup; drop unused code.

Create committer access macro references; the file is not yet included by the httpd config

### CODE REVIEW

**Comment by sebbASF** [comment]
Please can this be applied or rejected?

**Comment by sebbASF** [comment]
Ping?

**Comment by sebbASF** [comment]
ping?

**Comment by tonymontana100** [comment]
Enable

**Comment by tonymontana100** [comment]
Root

**Comment by clambertus** [comment]
sorry for the delay. this looks good to me.

**Pull request merged**
