### PR TITLE
Add entru for SDAP Incubating

### PR DESCRIPTION
**Pull request by lewismc**

### CODE REVIEW

**Comment by clambertus** [comment]
looks like you set up a git repo for the website, what is the purpose of this commit?

**Comment by lewismc** [comment]
@clambertus so we can host the Website code at Apache as well. Should this go somewhere else? we are looking at implementing GitPubSub. Thanks.

**Comment by clambertus** [comment]
gitpubsub and git repos use a different authentication system (LDAP). this commit only updates auth for subversion repos, which should not be necessary for a git-based website. you will need to submit an infra jira to get gitpubsub set up for your website repo.

**Comment by lewismc** [comment]
OK doke @clambertus so I this ticket should be closed off?

**Comment by gmcdonald** [comment]
Yeah this PR is not required.

**Pull request closed without merging**
